import"./assets/modulepreload-polyfill-B5Qt9EMX.js";/* empty css                      */const l=[{preview:"https://picsum.photos/id/1015/400/250",original:"https://picsum.photos/id/1015/1200/800",description:"Mountain lake"},{preview:"https://picsum.photos/id/1025/400/250",original:"https://picsum.photos/id/1025/1200/800",description:"Dog portrait"},{preview:"https://picsum.photos/id/1035/400/250",original:"https://picsum.photos/id/1035/1200/800",description:"River canyon"},{preview:"https://picsum.photos/id/1043/400/250",original:"https://picsum.photos/id/1043/1200/800",description:"Forest path"},{preview:"https://picsum.photos/id/1050/400/250",original:"https://picsum.photos/id/1050/1200/800",description:"Ocean pier"},{preview:"https://picsum.photos/id/1069/400/250",original:"https://picsum.photos/id/1069/1200/800",description:"Mountain landscape"},{preview:"https://picsum.photos/id/180/400/250",original:"https://picsum.photos/id/180/1200/800",description:"Workspace desk"},{preview:"https://picsum.photos/id/201/400/250",original:"https://picsum.photos/id/201/1200/800",description:"Person writing"},{preview:"https://picsum.photos/id/1/400/250",original:"https://picsum.photos/id/1/1200/800",description:"Laptop on desk"}],c=document.querySelector(".gallery");let i=0,r=null;const h=l.map(({preview:t,original:o,description:n},a)=>`<li class="gallery-item">
        <a class="gallery-link" href="${o}" data-index="${a}">
          <img class="gallery-image" src="${t}" alt="${n}" />
        </a>
      </li>`).join("");c.insertAdjacentHTML("beforeend",h);const e=y();document.body.append(e.element);c.addEventListener("click",f);e.element.addEventListener("click",b);function y(){const t=document.createElement("div");return t.className="gallery-modal",t.setAttribute("role","dialog"),t.setAttribute("aria-modal","true"),t.setAttribute("aria-label","Gallery image preview"),t.setAttribute("hidden",""),t.innerHTML=`
    <p class="gallery-modal__counter" aria-live="polite"></p>
    <button class="gallery-modal__button gallery-modal__button--close" type="button" aria-label="Close modal">×</button>
    <button class="gallery-modal__button gallery-modal__button--prev" type="button" aria-label="Previous image">‹</button>
    <div class="gallery-modal__content">
      <img class="gallery-modal__image" src="" alt="" />
    </div>
    <button class="gallery-modal__button gallery-modal__button--next" type="button" aria-label="Next image">›</button>
  `,{element:t,counter:t.querySelector(".gallery-modal__counter"),image:t.querySelector(".gallery-modal__image"),content:t.querySelector(".gallery-modal__content"),closeButton:t.querySelector(".gallery-modal__button--close"),prevButton:t.querySelector(".gallery-modal__button--prev"),nextButton:t.querySelector(".gallery-modal__button--next")}}function f(t){const o=t.target.closest(".gallery-link");o&&(t.preventDefault(),_(Number(o.dataset.index),o))}function b(t){if(t.target===e.element||t.target===e.closeButton){u();return}if(t.target===e.prevButton){p();return}t.target===e.nextButton&&d()}function _(t,o){i=t,r=o,s(),e.element.hidden=!1,document.body.classList.add("modal-open"),document.addEventListener("keydown",m),e.closeButton.focus()}function u(){e.element.hidden=!0,document.body.classList.remove("modal-open"),document.removeEventListener("keydown",m),r&&(r.focus(),r=null)}function p(){i=(i-1+l.length)%l.length,s()}function d(){i=(i+1)%l.length,s()}function s(){const{original:t,description:o}=l[i];e.image.src=t,e.image.alt=o,e.counter.textContent=`${i+1}/${l.length}`}function m(t){if(t.key==="Escape"){u();return}if(t.key==="ArrowLeft"){p();return}if(t.key==="ArrowRight"){d();return}t.key==="Tab"&&v(t)}function v(t){const o=[e.closeButton,e.prevButton,e.nextButton].filter(g=>!g.disabled),n=o[0],a=o[o.length-1];if(t.shiftKey&&document.activeElement===n){t.preventDefault(),a.focus();return}!t.shiftKey&&document.activeElement===a&&(t.preventDefault(),n.focus())}
//# sourceMappingURL=1-gallery.js.map
